---
apiVersion: v1
kind: Service
metadata:
  name: bookapp
spec:
  selector:
    app: bookapp
  ports: 
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookapp
  labels: 
    app: bookapp
spec:
  selector:
    matchLabels:
      app: bookapp
  template:
    metadata:
      labels:
        app: bookapp
    spec:
      containers:
      - name: bookapp 
        image: josephigbi/book_webapp
        ports:
        - containerPort: 5000
