apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  ports:
    - port: 3306
  selector:
    app: database
    tier: mysql
  type: ClusterIP 


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  selector:
    matchLabels:
      app: database
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: database
        tier: mysql
    spec:
      containers:
        - image: josephigbi/book_webappmysql
          name: database
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin
            - name: MYSQL_DATABASE
              value: flask2
          ports:
            - containerPort: 3306
              name: mysql
#---   
#          volumeMounts:
#            - name: mysql-persistent-storage
#              mountPath: /var/lib/mysql
#      volumes:
#        - name: mysql-persistent-storage
#          awsElasticBlockStore:
#            volumeID: EBS_VOLUME_ID
#            fsType: ext4
#---
